CREATE TABLE HISTORY (
    ID INTEGER PRIMARY KEY,
    PATIENT_ID INTEGER NOT NULL REFERENCES PATIENT(ID),
    CHRONIC_DISEASE VARCHAR NOT NULL,
    PREDISPOSITIONS VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);
