CREATE TABLE PATIENT_BRACELET (
    ID UUID PRIMARY KEY,
    PATIENT_ID UUID NOT NULL REFERENCES PATIENT(ID),
    BRACELET_ID UUID NOT NULL REFERENCES BRACELET(ID),
    COMPLAINT VARCHAR NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL
);
