CREATE TABLE PRONTUARY (
    ID UUID PRIMARY KEY,
    PATIENT_BRACELET_ID UUID NOT NULL REFERENCES PATIENT_BRACELET(ID),
    EMPLOYEE_ID UUID NOT NULL REFERENCES EMPLOYEE(ID),
    TEMPERATURE VARCHAR NOT NULL,
    ARTERIAL_PRESSURE VARCHAR NOT NULL,
    HEIGHT VARCHAR,
    WEIGHT VARCHAR
);
