CREATE TABLE CONSULTATION (
    ID UUID PRIMARY KEY,
    EMPLOYEE_ID UUID NOT NULL REFERENCES EMPLOYEE(ID),
    CREATED_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NOT NULL,
    PRONTUARY_ID UUID NOT NULL REFERENCES PRONTUARY(ID),
    ANNOTATIONS VARCHAR NOT NULL
);